### ISSUE TITLE
would you please release the code package 

### ISSUE THREAD

**Issue by wzl2611** [twhui/LiteFlowNet2#2]
you  have done a great  job.would you please release the code package ? Thank you very much

**Comment by twhui** [comment]
I will let you know if the code package is ready to release.

**Comment by ytongW** [comment]
Exciting work! waiting for your code~~~

**Comment by musicrainie** [comment]
Looking forward to the code!

**Comment by ErenBalatkan** [comment]
Look forward aswell

**Comment by dilipkumar25** [comment]
Same.. looking forward to the release.

**Comment by jianguolalala** [comment]
looking forward to your release

**Comment by twhui** [comment]
Hello all, the paper has been accepted in TPAMI. The code package is released!

**Comment by cdcseacave** [comment]
I might be new to this, can someone pls point me to the training code? I see only the testing code and trained models.
